openapi: 3.0.0
info:
  title: SKVF Kaninregister API
  description: API for managing bunnies and their owners/breeders
  version: "0.1"

tags:
  - name: BunnyRegistry
    description: Registry of bunnies and owners/breeders
    
paths:
  /login:
    post:
      tags: [BunnyRegistry]
      operationId: login
      summary: Starts an authenticated owner session
      requestBody:
        description: Owner credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDTO'
      responses:
        '200':
          description: Owner authenticated
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '401':
          description: Authentication failed
        '409':
          description: Already in session
          
  /logout:
    post:
      tags: [BunnyRegistry]
      operationId: logout
      summary: Ends an authenticated owner session
      responses:
        '200':
          description: Owner logged out
          
  /owners:
    post:
      tags: [BunnyRegistry]
      operationId: createOwner
      summary: Creates a new owner.
      requestBody:
        description: Owner to create, without ID
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/OwnerDTO'
      responses:
        '200':
          description: Owner created
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '400':
          description: Incoming OwnerDTO must not contain an ID, but must have a user name
        '401':
          description: Session NOT allowed
    get:
      tags: [BunnyRegistry]
      operationId: getOwners
      summary: Returns a list of owners.
      parameters:
        - name: onlyBreeders
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of owners
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerList'
        '401':
          description: Session required
                
  /owners/{id}:
    get:
      tags: [BunnyRegistry]
      operationId: getOwner
      summary: Returns an owner
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Owner
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '204':
          description: Non-public owner and not in session
        '401':
          description: Session required
        '404':
          description: Owner not found
    put:
      tags: [BunnyRegistry]
      operationId: updateOwner
      summary: Updates an existing owner.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Owner to update, missing fields are unchanged
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/OwnerDTO'
      responses:
        '200':
          description: Owner updated
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '400':
          description: If incoming OwnerDTO has an ID, it must match the path
        '401':
          description: Session required, of approved owner
        '404':
          description: Owner not found
    delete:
      tags: [BunnyRegistry]
      operationId: deleteOwner
      summary: Deletes an owner, removing it as breeder from bunnies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Owner deleted
        '400':
          description: Owner has bunnies
        '401':
          description: Session required, of owner
        '404':
          description: Owner not found
          
  /owners/{id}/activate:
    post:
      tags: [BunnyRegistry]
      operationId: activateOwner
      summary: Activates owner account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Activation data
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ActivationDTO'
      responses:
        '200':
          description: Owner activated
        '204':
          description: Owner already activated
        '400':
          description: Invalid user name or password
        '401':
          description: Session NOT allowed
        '404':
          description: Owner not found
        '409':
          description: User name already in use
          
  /owners/{id}/deactivate:
    post:
      tags: [BunnyRegistry]
      operationId: deactivateOwner
      summary: Deactivates owner account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Owner deactivated
        '401':
          description: Session required, of activated owner
        '404':
          description: Owner not found
          
  /owners/{id}/approve:
    post:
      tags: [BunnyRegistry]
      operationId: approveOwner
      summary: Approves storage/usage of owner data.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Owner approved
        '204':
          description: Approval failed
        '307':
          description: Approval ongoing, show Location to user  
        '401':
          description: Session required, of owner
        '404':
          description: Owner not found
          
  /owners/{id}/unapprove:
    post:
      tags: [BunnyRegistry]
      operationId: unapproveOwner
      summary: Revokes approval of storage/usage of owner data.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Owner unapproved
        '401':
          description: Session required, of approved owner
        '404':
          description: Owner not found
          
  /owners/{id}/password:
    put:
      tags: [BunnyRegistry]
      operationId: setPassword
      summary: Sets owner password.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Password data
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PasswordDTO'
      responses:
        '200':
          description: Password set
        '400':
          description: Invalid new password
        '401':
          description: Session required, of owner
        '404':
          description: Owner not found
          
  /owners/{id}/bunnies:
    post:
      tags: [BunnyRegistry]
      operationId: createBunny
      summary: Creates a new owned bunny.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Bunny to create, without ID
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/BunnyDTO'
      responses:
        '200':
          description: Bunny created
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyDTO'
        '400':
          description: Incoming BunnyDTO must not have an ID and if it has an owner, it must match the path
        '401':
          description: Session required, of approved owner
        '404':
          description: Owner not found
    get:
      tags: [BunnyRegistry]
      operationId: getOwnerBunnies
      summary: Returns the bunnies of an owner
      description: All bunnies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of bunnies
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyList'
        '401':
          description: Session required, of owner
          
  /owners/{owner}/bunnies/{bunny}:
    put:
      tags: [BunnyRegistry]
      operationId: updateBunny
      summary: Updates an owned bunny.
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: bunny
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Bunny to update, missing fields are unchanged. Owner may be different from path and will transfer bunny ownership.
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/BunnyDTO'
      responses:
        '200':
          description: Bunny updated
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyDTO'
        '400':
          description: If Incoming BunnyDTO has an ID, it must match the path.
        '401':
          description: Session required, of owner
        '404':
          description: Owner or bunny not found
    delete:
      tags: [BunnyRegistry]
      operationId: deleteBunny
      summary: Deletes a bunny
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: bunny
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Bunny deleted
        '401':
          description: Session required, of owner
        '404':
          description: Owner or bunny not found
      
  /bunnies:
    get:
      tags: [BunnyRegistry]
      operationId: findBunnies
      summary: Finds bunnies
      description: At least of criteria is required for a result
      parameters:
        - name: identifier
          in: query
          description: "Identifier template, with # as wildcard, for start of identifier"
          schema:
            type: string
        - name: name
          in: query
          description: Start of name
          schema:
            type: string
      responses:
        '200':
          description: Bunnies found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyList'
                
  /bunnies/{id}:
    get:
      tags: [BunnyRegistry]
      operationId: getBunny
      summary: Returns a bunny
      description: Any bunny
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Bunny
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyDTO'
        '404':
          description: Bunny not found
          
  /bunnies/{id}/revert:
    get:
      tags: [BunnyRegistry]
      operationId: revertBunnyOwner
      summary: Reverts bunny to previous owner
      description: The previous owner can revert a bunny if the new owner is not activated
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ownership reverted
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BunnyDTO'
        '204':
          description: Bunny has no public owner
        '400':
          description: No previous owner
        '401':
          description: Session required, of previous owner
        '404':
          description: Bunny not found
        '409':
          description: Current owner activated
          
  /bunnies/{id}/owner:
    get:
      tags: [BunnyRegistry]
      operationId: getBunnyOwner
      summary: Returns any public owner of the bunny
      description: A private owner can still be accessed using its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Public owner
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '204':
          description: Bunny has no public owner
        '404':
          description: Bunny not found or has no owner
          
  /bunnies/{id}/breeder:
    get:
      tags: [BunnyRegistry]
      operationId: getBunnyBreeder
      summary: Returns any public breeder of the bunny
      description: A private breeder can still be accessed using its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Public breeder
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OwnerDTO'
        '204':
          description: Bunny has no public breeder
        '404':
          description: Bunny not found or has no breeder

components:
  schemas:
    OwnerList:
      type: object
      properties:
        owners:
          type: array
          items: 
            $ref: '#/components/schemas/OwnerListDTO'
    OwnerListDTO:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userName:
          type: string
          readOnly: true
        breederName:
          type: string
    OwnerDTO:
      allOf:
        - $ref: '#/components/schemas/OwnerListDTO'
        - type: object
          properties:
            email:
              type: string
            publicOwner:
              type: boolean
            breeder:
              type: boolean
            publicBreeder:
              type: boolean
            
    LoginDTO:
       type: object
       required:
         - userName
         - password
       properties:
         userName:
           type: string
           description: Owner user name
         password:
           type: string
           description: Owner password
    ActivationDTO:
       type: object
       required:
         - userName
         - password
       properties:
         bunny:
           type: string
           description: Any bunny owned (required if owner has no previous user name)
         userName:
           type: string
           description: User name to set
         password:
           type: string
           description: Password to set
    PasswordDTO:
       type: object
       required:
         - currentPassword
         - newPassword
       properties:
         currentPassword:
           type: string
           description: Must match current password
         newPassword:
           type: string
           description: New password to set
    BunnyList:
      type: object
      properties:
        bunnies:
          type: array
          items: 
            $ref: '#/components/schemas/BunnyListDTO'
    BunnyListDTO:
      type: object
      properties:
        id:
          type: string
        owner:
          type: string
        name:
          type: string
    BunnyDTO:
      allOf:
        - $ref: '#/components/schemas/BunnyListDTO'
        - type: object
          properties:
            previousOwner:
              type: string
              readOnly: true
            breeder:
              type: string